{% set name = "griffe-pydantic" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/griffe_pydantic-{{ version }}.tar.gz
  sha256: ca3595df7a586343391ea976c456b8142750c68a5901e593ab6529bd8120275a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pdm-backend
    - pip
  run:
    - python >=3.9
    - griffe >=0.49
    - pydantic

test:
  imports:
    - griffe_pydantic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mkdocstrings/griffe-pydantic
  summary: Griffe extension for Pydantic.
  license: ISC
  license_file: LICENSE
  doc_url: https://mkdocstrings.github.io/griffe-pydantic/

extra:
  recipe-maintainers:
    - SimonBoothroyd
