{% set name = "griffe-pydantic" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/griffe_pydantic-{{ version }}.tar.gz
  sha256: 9c5a701cc485dab087857c1ac960b44671acee5008aaae0752f610b2aa82b068

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - griffe >=0.49
    - pydantic

test:
  imports:
    - griffe_pydantic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mkdocstrings/griffe-pydantic
  summary: Griffe extension for Pydantic.
  license: ISC
  license_file: LICENSE
  doc_url: https://mkdocstrings.github.io/griffe-pydantic/

extra:
  recipe-maintainers:
    - SimonBoothroyd
