{% set name = "griffe-pydantic" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/griffe_pydantic-{{ version }}.tar.gz
  sha256: 4d7cddda2d30ef7814cd3d78af854d6fcc14f3f170bd07360babbec62673d4ca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - griffelib >=2.0

test:
  imports:
    - griffe_pydantic
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/mkdocstrings/griffe-pydantic
  summary: Griffe extension for Pydantic.
  license: ISC
  license_file: LICENSE
  doc_url: https://mkdocstrings.github.io/griffe-pydantic/

extra:
  recipe-maintainers:
    - SimonBoothroyd
    - stanmart
